# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Build"
  lane :build_debug_app do
    gradle(task: "assembleDebug")
  end

  desc "Submit to Firebase"
  lane :beta do
    gradle(task: "assembleRelease")
#    firebase_app_distribution(
#      app: "1:300830567303:android:9b9ba2ce17104d0c",
#      testers: "brianoh@circleci.com",
#      apk_path: "app/build/outputs/apk/release/app-release.apk",
#      firebase_cli_token: ENV["FIREBASE_TOKEN"]
#    )
  end
end
